# Generated by Django 2.0.5 on 2018-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hungry_No_More', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
        migrations.AddField(
            model_name='user',
            name='station',
            field=models.CharField(default='NDLS', max_length=10),
            preserve_default=False,
        ),
    ]
