# Generated by Django 2.0.5 on 2018-06-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hungry_No_More', '0002_auto_20180619_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='sabka apna naam', max_length=100),
            preserve_default=False,
        ),
    ]
