# Generated by Django 2.0.5 on 2018-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hungry_No_More', '0004_auto_20180624_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default='08130520072', max_length=12),
            preserve_default=False,
        ),
    ]
